#! /bin/awk -f 
# -*- awk -*-
BEGIN {
  N=1;
  print "set xrange [100:400]";
  print "set yrange [100:400]";
}
{
  for (i=1;i<N+1;i++)
    {
      getline;
      split($0,a," ");
      x[i]=a[6];y[i]=a[7];s[i]=1/a[8];acc[i]=a[4];
    }

  print "clear"
  print "set multi";
  print "plot \"-\" u 2:1 w p 2 10";
  
  K=0;
  for (i=1;i<N+1;i++)
    if (acc[i] == 1)
      {
	dx=x[i]-x[N];dy=y[i]-y[N];
	r=sqrt(dx*dx + dy*dy);
	print x[i],y[i],dx,dy,r,s[i],acc[i];
      }
    else K=1;
   
  printf("e\n");

  if (K==1)
    {
      print "plot \"-\" u 2:1 w p 1";
      for (i=1;i<N+1;i++)
	if (acc[i] == -10)
	  {
	    dx=x[i]-x[N];dy=y[i]-y[N];
	    r=sqrt(dx*dx + dy*dy);
	    print x[i],y[i],dx,dy,r,s[i],acc[i];
	  }
      print("e\n");
    }
  print "plot \"-\" u 2:1 w p 3 6";
  print x[N],y[N],dx,dy,r,s[N],acc[N];
  printf("e\n");

  for (i=1;i<N;i++)
    print "set noarrow ",i;
    
  for (i=1;i<N+1;i++)
    print "set arrow ",i," from ",y[i],",",x[i]," to ",y[i]+3*s[i],",",x[i]

  print "set nomulti";
  printf("pause -1 \"Hit RETURN\"\n");
  N++;
}
